<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-09-02 12:18
=======
# Generated by Django 5.2.5 on 2025-08-31 15:34
>>>>>>> f408c826089a138d6b665aa4177820c10113a8bc

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publication_year', models.IntegerField()),
<<<<<<< HEAD
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.author')),
=======
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.author')),
>>>>>>> f408c826089a138d6b665aa4177820c10113a8bc
            ],
        ),
    ]
